### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by bl4ckswordsman** [bl4ckswordsman/abc_app#1]
# Todo:
- [x] Add language selector
- [x] Fully implement working button pop up on click
- [x] Make large button clicks change button color
- [x] Show emojis on large button clicks
- [x] Upgrade to Material You look, feel and shapes (+dark theme support)
- [x]  Make android app updateable via github version release check
- [x] Add a settings page
- [x] Make large button clicks play random sounds bd626f040c0fc89fd83c54195907caaeaea85ded
- [ ] Add action button in large button page to play relevant sound or pronunciation audio
- [ ] Add action button in large button page disable emoji timeout

# Minor issues:
- [x] Add 🦆 for the "A" button 86e1934ebf04f630d693d27520529392436ca1c9

# Maybe:
- [x] #64
- [x] #61
- [x] Investigate the web deployment for the app
- [ ] Create app logo and/or splash screen animation

**Comment by JoyB4y** [comment]
I didn't want to create a new "Issue" so I'm going to write it here: There's an emoji in your code that doesn't fit with the letter it's correlated to-->"👂" with the letter "O".

**Comment by bl4ckswordsman** [comment]
> I didn't want to create a new "Issue" so I'm going to write it here: There's an emoji in your code that doesn't fit with the letter it's correlated to-->"👂" with the letter "O".

Yeah I saw it too, thanks. Haven't done any QC so ye
